### PR TITLE
Refactors project to reduce obsfucation and increase extendability and linear flow

### PR DESCRIPTION
**Pull request by douglasg14b**
Words on what has changed will be expanded upon.

### General Consistency & Code Quality

* Scattered Enums have been moved to a single file
* In-line declared constants in classes and even methods have been moved to a `Constants` class
* In-line out-of-scope logic has been moved to a `Utilities` class as either extension methods or as static methods
* Files containing many type declarations have had those declarations moved into their own files **(Incomplete)**
* Models (POCOs) have been moved to a shared folder/namespace **(Incomplete)**

### Command Builder

I have largely rewritten this, the goal being to break much of the in-line declarations/configs and single-line call chains out into their own methods contained within their own classes. 

On one hand this does increase the verbosity of the command builders, but on the other this makes the call flow more linear, makes it easier to reason through & parse, and makes it easier to extend and modify without producing side effects.

* `StreamFile` has been replaced by files for each type. The purpose of this is to not kludge one model into multiple use cases, this kind of usage makes it more difficult to make changes, or to know what certain field/props are actually for.
* `CommandBuildResult` has been replaced by results for ffmpeg and mp4box. Just like `StreamFile` this resolves issues related to kludging multiple use cases into a single model. My commit comments have more information.
* The builder pattern I started is based on my discoveries for my [console tables library](https://github.com/douglasg14b/BetterConsoleTables/tree/Version2/src/BetterConsoleTables/Builders), on developing a fluent API. Unfortunately after I had set it up I realized that the commands where simpler to build than expected, and the interfaces are largely useless.

### Encoder

This has been modified to support new changes made to the command builder and it's types. The large `GenerateDash` method has be split into multiple supporting methods. A config class has been created to move config responsibility out of the `GenerateDash` method.

* New Methods split out from `GenerateDash`
* Config usage over many arguments
* Progress reports for `ffmpeg` are delivered over stdOut instead of error

### Tests

Tests have largely been rewritten for the new encoder. See commit extended messages for more.

## To Do:

- [x] Clean up my classes and interfaces
- [x] Create files for each (non-enum) type declaration (Largely for my new code)
- [x] XML comments on missing items
- [x] Finish model organization
- [x] Dead code removal
- [x] Move certain constrained `string` fields over to `Enums`

### CODE REVIEW

**Comment by douglasg14b** [comment]
@bloomtom This is in a ready to use state. 

I have some cleanup to do still on my code, some organizing to make consistent, and dead code removal to perform. But other than those misc things, my first-pass go at this is complete.

`Encoder2` is a  placeholder name for the time being.

Many of my commits have extended messages with more information on changes and decisions.

What you see here is just refactor results, no new features have really been added.

**Comment by douglasg14b** [comment]
The cleanup and commenting is now seemingly complete.

**Comment by douglasg14b** [comment]
@bloomtom For the v2, I would greatly appreciate the merge not being squashed. I put specific effort into each commit message to ensure clarity, and try to keep commits granular and scoped. It's a bit of a slap to the face to have contributions fully squashed.... 

If some commits are frivolous (Which some are), let me know and I can squash them down specifically to keep your history clean.

Thanks for accepting the changes.

**Comment by bloomtom** [comment]
Since you feel so strongly about it, I've redone the merge to preserve individual commits.

**Pull request merged**
